theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: Project Manager

# 对你自己的简洁描述
description: Project managers are responsible for turning grand ideas into deliverable projects, products, or features. In a word, they deliver value. 

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: Fiona Wang

# 你的联系方式
phone: 188888888888

# 你的邮箱
email: fionawang888@hotmail.com

# 你目前的住址
address: Melbourne

# 你毕业院校
school: RMIT

# 你的专业
profession: Project Manager

# 你的学位
degree: Bachelor degree

# 你获得过的证书或奖励
credential: winner of art design(media) in 2018 Melbourne International Arts Festival
